### ISSUE TITLE
Image preprocessing on Brain and Liver dataset

### ISSUE THREAD

**Issue by nono-zz** [raun1/ASC-NET#1]
Hi, 

Thank you for illustrating your excellent work, I want to know how you preprocess the medical images, **especially the LiTS dataset**? I've downloaded the dataset and cut them to axial slices, but the anomalous area is so not obvious in the raw images.

I've used the histogram equalization embedded in open cv packages, but it erodes the normal area as well. Hope you could help me with this, thank you!

Bests,
Zhaoxiang

**Comment by raun1** [comment]
Hello 

Thanks for writing. You can segment the liver region with a simpler preprocessing method. Then do a histogram normalization to get the same result on the segmented liver. 
Thanks

**Comment by raun1** [comment]
Err I can't recall right now but it should be somewhere in the paper I might have just done a [0 1] normalization after segmenting the liver.

**Comment by nono-zz** [comment]
Okay, so segment the liver region from abdominal image, and then [0 1] normalization? I'll try that, thank you so much!

**Comment by raun1** [comment]
Goodluck!
